### ISSUE TITLE
OpenMQTTGateway and Theengs

### ISSUE THREAD

**Issue by zzpenguin** [theengs/gateway#67]
I recently installed TheengsGateway as a Home Assistant addon and added the line below to my OpenMQTTGateway code
`#define MQTTDecodeTopic "home/TheengsGateway/commands"`

However it seems that decode commands are being sent to 
`home/OpenMQTTGateway/BTtoMQTT/home/TheengsGateway/commands`
and are not Published anywhere

on the MQTT server instead of
`home/TheengsGateway/commands`

I can manually send commands to `home/TheengsGateway/commands` and they are decoded properly and Published to `home/TheengsGateway/BTtoMQTT`

Am I missing something?

**Comment by 1technophile** [comment]
That's a good question, and I will document this feature more for the next release.
On the ESP32 side you can take those parameters to have a gateway that publish undecided messages:
https://github.com/1technophile/OpenMQTTGateway/blob/fd8c3a79ae3b655b388acb6cd270eedc2f220f53/platformio.ini#L430

Mainly `  '-DMQTTDecodeTopic="undecoded"'` is the difference with your env I think

On the addon configuration side, you can use this 
![image](https://user-images.githubusercontent.com/12672732/197526765-47666af0-1486-4dfa-84d3-7ab8428eb347.png)

So that Theengs Gateway is going to take all the undecided coming traffic from any ESP32 OpenMQTTGateway.

This is how it will look like in your broker:
![image](https://user-images.githubusercontent.com/12672732/197527039-2d0f79e9-092f-4e0b-94c1-1364153a01d4.png)
